homepage/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('jadwal/', views.jadwal, name = 'jadwal'),
    path('delete/', views.delete, name = 'delete')
]

ppw/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models
from django.utils import timezone
import datetime
# from django.forms import ModelForm

# Create your models here.
class Schedule(models.Model):
    name = models.CharField(max_length = 25)
    category = models.CharField(max_length = 25)
    place = models.CharField(max_length = 25)
    date = models.DateTimeField()

    # def __str__(self):
    #     return self.name

homepage/forms.py
from django import forms
from .models import Schedule
from django.forms import ModelForm
import datetime

CATEGORY_LIST = [
    ('rapat', 'Rapat'),
    ('kelas', 'Kelas'),
    ('belajar', 'Belajar'),
    ('acara', 'Acara'),
    ('lain-lain', 'Lain-lain'),
    ('deadline', 'Deadline'),
]

class ScheduleForm(ModelForm):
    category = forms.CharField(max_length = 25, label='Kategori jadwal', widget=forms.Select(choices=CATEGORY_LIST))
    class Meta:
        model = Schedule

        fields = ["name", 'category', 'place', 'date']

homepage/views.py
from django.shortcuts import render, redirect
from .forms import ScheduleForm
from .models import Schedule
from django.http import HttpResponse
from django.http import HttpResponseRedirect
import datetime

# Create your views here.
def index(request):
    return render(request, 'index.html')

def jadwal(request):
    if request.method == 'GET':
        form = ScheduleForm()
    elif request.method == 'POST':
        form = ScheduleForm(request.POST)
        print(request.POST)
        if form.is_valid():
            new_schedule = Schedule(
                name = form.data['name'],
                category = form.data['category'],
                place = form.data['place'],
                date = form.data['date'],
            )

            new_schedule.save()
            form = ScheduleForm()
        return HttpResponseRedirect('/jadwal/')
    
    schedules = Schedule.objects.all()
    context = {
        'form': form,
        'schedules': schedules,
    }
    return render(request, 'jadwal.html', context)

def delete(request):
    Schedule.objects.filter(id = int(request.GET.get('arg', ''))).delete()
    return HttpResponseRedirect('/jadwal/')

homepage/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Bree Serif">
    
    <script src="https://kit.fontawesome.com/26197ec3bf.js"></script>

    <title>Profil Saya</title>
</head>
<body>
    <div id="header">
        <div class="nav-container">
            <div class="linkbox"><a href="#biodata"><b>Biodata</b></a></div>
            <div class="linkbox"><a href="#tentang"><b>Tentang</b></a></div>
            <div class="linkbox"><a href="#riwayat"><b>Riwayat</b></a></div>   
        </div>
        <div class="img-container"><img src="{% static 'images/foto_saya_cropped.jpg' %}" alt="foto_saya"></div>
        <h1>Muhammad Azis Husein</h1>
    </div>

    <div id="biodata">
        <h1>Biodata</h1>
        <div class="container">
            <ul>
                <li><b>Nama Lengkap:</b></li>
                <li>&emsp; Muhammad Azis Husein</li>
                <li><b>Nama Panggilan:</b></li>
                <li>&emsp; Azis</li>
                <li><b>NPM:</b></li>
                <li>&emsp; 1806191622</li>
                <li><b>Tempat Kuliah:</b></li>
                <li>&emsp; Fasilkom UI</li>
                <li><b>Angkatan:</b></li>
                <li>&emsp; 2018</li>
                <li><b>Hobi:</b></li>
                <li>&emsp; Baca, Coding, Main</li>
            </ul>
        </div>
    </div>

    <div id="tentang">
        <h1>Tentang Saya</h1>
        <div class="container2">
            <p>Saya adalah seseorang yang ramah dan mudah berteman. Untuk mengetahui tentang saya lebih banyak, silakan kunjungi media sosial saya.</p>
        </div>

        <div class="medsos">
            <a href="https://www.instagram.com/muhammadazishusein"><i class="fab fa-instagram"></i></a>
            <a href="https://www.linkedin.com/in/muhammad-azis-h/"><i class="fab fa-linkedin"></i></a>
            <a href="https://gitlab.com/muhammadazishusein"><i class="fab fa-gitlab"></i></a>
            <a href="https://medium.com/@muhammadazishusein"><i class="fab fa-medium-m"></i></a>
        </div>
    </div>

    <div id="riwayat">
        <h1>Riwayat</h1>
        <div class="box-riwayat">
            <div class="logo-container">
                <img src="{% static 'images/logosma14.png' %}" alt="SMA 14 Jakarta">
            </div>
            <div class="info-riwayat-container">
                <h3>SMA Negeri 14 Jakarta 2015-2018</h3>
                <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt eaque nemo tenetur libero atque itaque ad quod neque asperiores natus quasi quisquam, laboriosam rerum nam voluptas reiciendis quam. Saepe, assumenda?
                </p>
            </div>
        </div>

        <div class="box-riwayat">
            <div class="logo-container">
                    <img src="{% static 'images/fasilkom ui.png' %}" alt="Fasilkom UI">
            </div>
            <div class="info-riwayat-container">
                <h3>Fakultas Ilmu Komputer Universitas Indonesia 2018-...</h3>
                <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt eaque nemo tenetur libero atque itaque ad quod neque asperiores natus quasi quisquam, laboriosam rerum nam voluptas reiciendis quam. Saepe, assumenda?
                </p>
            </div>
        </div>

        <p>Copyright &copy; Muhammad Azis Husein</p>
        <a href="{% url 'homepage:jadwal' %}">klik di sini untuk info selanjutnya</a>
    </div>

    <!-- <script src="./js/bootstrap.js"></script> -->
</body>
</html>

homepage/templates/jadwal.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <script src="https://kit.fontawesome.com/26197ec3bf.js"></script>

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <!-- XDSoft DateTimePicker -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Bree Serif">
    
    <title>Jadwal Saya</title>
</head>

<body>
    <div id="list-jadwal">
        <h1>Jadwal Saya</h1>
        <div class="container-table">
            <table class="table">
                <thead>
                    <tr>
                    <th scope="col">Nama</th>
                    <th scope="col">Kategori</th>
                    <th scope="col">Tempat</th>
                    <th scope="col">Waktu</th>
                    <th scope="col">Hapus</th>
                    </tr>
                </thead>
                {% for schedule in schedules %}
                <tbody>
                    <tr>
                    <td>{{ schedule.name }}</td>
                    <td>{{ schedule.category }}</td>
                    <td>{{ schedule.place }}</td>
                    <td>{{ schedule.date }}</td>
                    <td><a class="btn btn-danger" href="/delete/?arg={{schedule.id}}">Delete</a></td>
                    </tr>
                </tbody>
                {% endfor %}
            </table>
        </div>
    </div>

    <div id="ppw2">
        <h1>Schedule Form</h1>
        <div class="form-container">
            <!-- <form id="form" action="{ % url homepage:jadwal % }" method="POST"> -->
            <form id="form" action="/jadwal/" method="POST">
                {% csrf_token %}
                {{ form }}
                <button type="submit">SUBMIT</button>
            </form>
        </div>
        <a href="{% url 'homepage:index' %}">Kembali ke halaman utama</a>
    </div>

    <script>
        $(function () {
            $("#id_date").datetimepicker({
            format: 'Y-m-d H:i',
            });
        });
    </script>
</body>
</html>